from pydantic import BaseModel, Field
from typing import List, Dict, Any

class PerceptionPacket(BaseModel):
    """
    Contains all the information an entity perceives at the start of a turn.
    This is generated by the Game Master for each entity.
    """
    recipient_id: str = Field(..., description="The ID of the entity receiving this packet.")
    turn_number: int = Field(..., description="The current turn number.")
    narrative_synopsis: str = Field(..., description="A high-level narrative of events the entity witnessed or was involved in.")
    detailed_interactions: List[str] = Field(default_factory=list, description="Granular descriptions of specific, relevant interactions.")
    metadata_updates: Dict[str, Any] = Field(default_factory=dict, description="Direct updates to the entity's own state (e.g., resource changes).")

class IntentStatement(BaseModel):
    """
    Represents an entity's declared actions for the turn.
    This is generated by an Entity Agent and submitted to the Game Master.
    """
    actor_id: str = Field(..., description="The ID of the entity declaring the intent.")
    high_level_action: str = Field(..., description="A summary of the intended action.")
    thought_process: str = Field(..., description="The rationale and motivation behind the action.")
    specific_interactions: List[str] = Field(default_factory=list, description="A breakdown of specific sub-actions to be taken.")
